### PR TITLE
2019.1.3 Compatibility + Show Source feature

### PR DESCRIPTION
**Pull request by dkarlinsky**
- Updated Intellij version to 2019.1.3 and fixed breakage due to changes in Scala plugin
- New feature - "Show source" displays the generated source instead of saving to file:
screen

- New template: specs2-fluent-matcher.vm

### CODE REVIEW

**Comment by x-hansong** [comment]
Thank you for your contribution! It's a great job!

**Comment by x-hansong** [comment]
I found a problem that the "show source" dialog editor can't scoll when the code is longer than the  height of dialog.

**Comment by dkarlinsky** [comment]
Hey,
Actually, after I haven't heard back from you for a while about this PR, I
continued working on the plugin in my fork. I fixed the scrolling issue and
made a lot of other improvements.
For example there is a way to run a template on a dummy class structure as
you are working on it.
I also added support for groovy based templates.
I didn't know if you were still maintaining the plugin, so I was going to
publish my fork separately, but I can make a PR out of it.
It will be a big one though :)

**Comment by x-hansong** [comment]
You did a awesome job! I am glad to bring the new features you add to other users and record your contribution on the introdution of plugin. I will take more time on the project and if you have more ideas we can disscuss them together.

**Comment by dkarlinsky** [comment]
Cool!
I'm on vacation right now, travelling through Australia.
I may find time (and wifi) to create the PR out here.
If not, I'll do it when I get back home (10 days from now)

**Pull request merged**
